#!/bin/bash

NONE='\033[00m'
RED='\033[1;31m'
PURPLE='\033[01;35m'

ROOT_DIR=$(dirname "$(realpath $0)")

echo -e "Welcome to ${PURPLE}UNIPHILER${NONE}, the compiler you ${RED}love${NONE}!"

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 [SOURCE]"
    exit 1
fi

SOURCE=$1
OUT_J="${SOURCE%.*}.j"
TARGET_DIR=$(dirname $SOURCE)

echo -e "Compiling: ${SOURCE}"
swipl -q -t halt ${ROOT_DIR}/src/compile_jvm.prolog ${SOURCE} > ${OUT_J}
echo -e "Generated: ${OUT_J}"

echo -e "Compiling: ${OUT_J}"
java -jar ${ROOT_DIR}/lib/jasmin.jar ${OUT_J} -d ${TARGET_DIR}
